# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/tttest202211263',
                'doc_host': 'https://jbwhit.github.io',
                'git_url': 'https://github.com/jbwhit/tttest202211263',
                'lib_path': 'tttest202211263'},
  'syms': {'tttest202211263.core': {'tttest202211263.core.foo': ('core.html#foo', 'tttest202211263/core.py')}}}
